config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: :registrations }

  resources :users, only:[ :index, :show, :edit, :update ] do
   resources :bookings, except: [ :destroy ]
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  validates :student_id, presence: true
  validates :teacher_id, presence: true
  belongs_to :teacher, class_name: "User", foreign_key: "teacher_id"
  belongs_to :student, class_name: "User", foreign_key: "student_id"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :teacher_bookings, class_name: "Booking", foreign_key: "teacher_id"
  has_many :student_bookings, class_name: "Booking", foreign_key: "student_id"
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  searchkick searchable: [:skill]
end

# http://railscasts.com/episodes/163-self-referential-association
# has_many :bookings
# has_many :teachers, :through => :bookings
# has_many :inverse_bookings, :class_name => "Teacher", :foreign_key => "teacher_id"
# has_many :inverse_teachers, :through => :inverse_bookings, :source => :user

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = current_user
    @bookings = Booking.all.where(student: current_user)
    @teaching = User.where(skill: "Teaching")
    redirect_to users_path if @bookings.empty?
  end


  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @user = current_user
    @teacher = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.teacher_id = User.find(params["booking"]["teacher_id"].to_i).id
    @booking.student_id = current_user.id
    if @booking.save
      redirect_to user_booking_path(current_user, @booking)
    else
      redirect_to users_path()
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user)

  end

  private

  # def booking_params
  #   params.require(:booking).permit(:user_id, photo)
  # end
end


#########################ALEX WAY##########################
 # def new
 #    @teacher = User.find(params[:user_id])
 #    @booking = Booking.new
 #  end

 #  def create
 #    @booking = Booking.new(booking_params)
 #    @booking.teacher = User.find(params[:user_id])
 #    @booking.student = current_user
 #    @booking.save
 #  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(resource)
      user_bookings_path(resource)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    User.reindex
    if params[:query].present?
      @teachers = User.search(params[:query])
      markers
    else
      @teachers = User.all.where.not(latitude: nil, longitude: nil).where(teacher: true)
      markers
    end
  end

  def show
    @user = User.find(params[:id])
    @markers = [{ lng: @user.longitude, lat: @user.latitude }]
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  private

  def markers
    @markers = @teachers.map do |teacher|
      {
        lng: teacher.longitude,
        lat: teacher.latitude
      }
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :teacher, :address, :location, :skill, :biography)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="bookings-container">
  <div class="list-of-bookings">

      <div class = user-welcome>
     <h3>WELCOME BACK! <b><%= @user.first_name%></h3></b>
      <br><h4> <p>Your account name:<%= @user.email%></h4>
      </div>
      <div class="cards-bookings style="width: 18rem;">
       <div class="card-body">

        <% @bookings.each do |booking| %>


        <h1 class="booking-info"><p>Your teacher for the booking is </p><%= User.find(booking.teacher_id).first_name %></h1>


        <br><%= link_to "add bookings", users_path %>
        <br><%= link_to "delete the booking", booking_path(booking), method: :delete %>
        <% end %>
    </div>
  </div>
  </div>


  <div class="profile-section">

    <div id="profile-image">
    <%= cl_image_tag current_user.photo%>
    </div>

    <div id="personal-info">
      <div class = upload-picture >
        <%= link_to edit_user_registration_path do %>
        <button type="button" class="btn btn-secondary"
         <span class="btn-label"><i class="fa fa-pencil"></i></span>Upload You Picture Here</button>
        <% end %>




      </div>

    </div>
  </div>
  <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>

app/views/bookings/new.html.erb
<div class="container container-confirmation">
  <h1>You are almost there...</h1>
  <div class="confirmation-card">
    <div class="confirmation-text">
      <h2>Please review and confirm your request's details:</h2>
    </div>
    <div class="confirmation-details">
      <h2><strong><%= @teacher.skill %></strong> lessons with <strong><%= @teacher.first_name %></strong></h2>
    </div>
  </div>
  <div class="buttons-users-show">
    <%= link_to "Go back", user_path(@teacher), class: "btn btn-user btn-all-teachers" %>
    <%= simple_form_for [@user, @booking] do |f| %>
      <%= f.input :teacher_id, :as => :hidden, :input_html => { :value => @teacher.id }%>
      <%= f.submit "Confirm", class: "btn btn-secondary btn-card btn-booking-teacher" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container container-confirmation">
  <h1>Great!</h1>
  <div class="confirmation-card">
    <div class="confirmation-text">
      <h2>Your lesson booking id is <strong><%= @booking.id %></strong></h2>
    </div>
    <div class="confirmation-details">
      <p>As soon as <strong><%= @booking.teacher.first_name %></strong> confirms your request, we will send you an email to <strong><u><%= @booking.student.email %></strong></u></p>
    </div>
  </div>
  <div class="buttons-users-show">
    <%= link_to "Go to home page", root_path, class: "btn btn-secondary btn-card btn-booking-teacher" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>LessonFly</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

      <%= yield %>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="logo-footer">
        <%= link_to "LessonFly.", root_path, class: "logo"%>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="gradiant"></div>
  <div class="video">
  <%= video_tag "timelapsesky.mp4", autoplay: "autoplay", id: "video", muted: true, width: "100%", loop: "true", :class => "video"%>
  </div>


  <div class="header-container">

    <h1><b>LessonFly</b></h1>
    <p>Share your knowledge, Learn from others!</p>
    <div class="new-search">
      <%= form_tag users_path, method: :get, class: "form search-skills" do %>
        <%= text_field_tag :query,
          params["#{:query}?size=5"],
          class: "form-control search",
          placeholder: "Search Skills"
        %>
      <% end %>
    </div>
  </div>

<!--   <div class="search-bar">
    <input type="text" placeholder="JOIN THE COMMUNITY....">
    <div class="search"></div>
  </div> -->
      <div class="container text-center banner-2">

            <h1 class="section_title">Welcome to LessonFly community.</h1>
            <p class="normal_text">
                  Your extraordinary one on one fun tutoring experience start here! To be able to Learning Gaining Teaching.<br>You can create your own classes or attend someone else's trainings using our  platform to directly connect with the person from whenever you want!<br>Discover <span class="bold"><b>LESSONFLY</b></span> and start now your fun & enjoyable tutoring experience.
            </p>

      </div>


      <!-- <hr class="line line-top1 "> -->

      <div class="row cards-landing-page" id="scroll-down">


        <div class="col-lg-4 text-center card-landing">
          <img class="rounded-circle" src="https://cdn.dribbble.com/users/1973532/screenshots/5059462/illustration_students.png" alt="Generic placeholder image" width="200" height="200">
          <h1>Teach.</h1>
          <p>Share with other what you know, and be rewarded by it. Our students are dedicated and willing to learn what you teach. Digital tools save you time</p>
          <p><a class="btn btn-secondary btn-card" href="#" role="button">View details</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4 text-center card-landing">
          <img class="rounded-circle" src="https://cdn.dribbble.com/users/46302/screenshots/5092379/school.png" alt="Generic placeholder image" width="200" height="200">
          <h1>Learn.</h1>
          <p> Expand your horizons learning new things. Whether for fun or to advance your career, learn from experienced people on one-on-one sessions</p>
          <p><a class="btn btn-secondary btn-card" href="#" role="button">View details</a></p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4 text-center card-landing">
          <img class="rounded-circle" src="https://cdn.dribbble.com/users/369527/screenshots/4347634/pietrasiak_data_center2.png" alt="Generic placeholder image" width="200" height="200">
          <h1>Connect.</h1>
          <p>The platform provides a secure and trusted place where experienced people teach avid learners making use of digital tools to let you focus on what matters</p>
          <p><a class="btn btn-secondary btn-card" href="#" role="button">View details</a></p>
        </div><!-- /.col-lg-4 -->

      </div>
<!--  -->
      <!-- <hr class="line line-top line-bottom"> -->
      <!-- /.row -->

            <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">One-on-one. <span class="text-muted">Connecting Digital + Real.</span></h2>
          <p class="lead">LessonFly provides digital tools that help students and teachers find each other. With a large variety of topics you will find what you are looking for. Take advantage of our frameworks to book and pay classes. And use the time for what matters: <strong>Learn and Teach</strong>!</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="https://cdn.dribbble.com/users/70808/screenshots/5090953/graduate.jpg" alt="Generic placeholder image" style= "width: 500px; height: 500px; max-width: 100%; border-radius: 20px; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
        </div>
      </div>

     <!--  <hr class="line line-top line-bottom"> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="fixed-top navbar navbar-expand-sm navbar-light navbar-lewagon" style="<%= "background-color: transparent" if params[:action] == "home" %> ">

  <%= link_to "LessonFly", root_path, class: "navbar-brand logo"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav">

      <div class="nav-item btn-ghost" id="scroll">

        <a class="nav-link" href="#scroll-down">Features</a>

      </div>
    </div>
  </div>



  <div class="dropdown mr-left nav-item">

      <% if !current_user %>

        <div class="nav-item left-button btn-ghost">
            <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
        </div>

        <div class="nav-item left-button btn-ghost">
            <%= link_to "Log-in", new_user_session_path, class: "nav-link" %>
        </div>

      <% elsif !current_user.teacher %>
          <div class="nav-item left-button btn-right-margin btn-ghost">
            <%= link_to "Become a teacher", edit_user_path(current_user), class: "nav-link" %>
          </div>

        <!--         "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/featured/?{drink},{cocktail}<%= (1..10000).to_a.sample %>)" -->

        <%= image_tag "https://images.unsplash.com/photo-1524593689594-aae2f26b75ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80", class: "avatar-nav dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My account", user_path(current_user), class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>


        </div>

      <% else %>

      <div class="nav-item dropdown">

        <%= image_tag "https://images.unsplash.com/photo-1524593689594-aae2f26b75ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80", class: "avatar-nav dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My account", user_path(current_user), class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>

      </div>


      <% end %>

  </div>
</div>

<script>
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
            behavior: 'smooth'
        });
    });
});
</script>

app/views/users/edit.html.erb
<div class="become-teacher-container">

  <div class="form-become-teacher">
    <%= simple_form_for [@user] do |f| %>
      <h1><%= "Complete your profile to become a teacher" %></h1>
      <%= f.input :first_name,
                      required: true,
                      label: false,
                      placeholder: 'First name',
                      autofocus: true,
                      input_html: { autocomplete: "first-name" }%>
      <%= f.input :last_name,
                      required: true,
                      label: false,
                      placeholder: 'Last name',
                      autofocus: true,
                      input_html: { autocomplete: "last-name" }%>
      <%= f.input :email,
                      required: true,
                      label: false,
                      placeholder: 'Email address',
                      autofocus: true,
                      input_html: { autocomplete: "email" }%>
      <%= f.input :teacher, as: :radio_buttons,
                      label: "Do you want to become a teacher?" %>
      <%= f.input :address,
                      required: true,
                      label: false,
                      placeholder: 'Your address',
                      autofocus: true,
                      input_html: { autocomplete: "address" }%>
      <%= f.input :skill,
                      required: true,
                      label: false,
                      placeholder: 'What do you want to teach?',
                      autofocus: true,
                      input_html: { autocomplete: "skill" }%>
      <%= f.input :biography,
                      required: true,
                      label: false,
                      placeholder: 'Tell us more about you, this information will help the students to choose you',
                      autofocus: true,
                      input_html: { autocomplete: "skill" }%>

      <div class="buttons-users-show">
      <%= f.button :button, "Cancel", type: "reset", class: "btn btn-secondary btn-all-teachers" %>
      <%= f.submit "Create", class: "btn btn-secondary btn-card btn-booking-teacher" %>
    <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main-container-index-teachers">

  <div class="cards-all-teachers">
  <% @teachers.each do |user| %>

    <div class="card-teacher">
      <%= cl_image_tag(user.photo, width: 400, height: 300) %>
      <div class="card-teacher-infos">
        <div>
          <h2><%= link_to user.skill, user_path(user) %></h2>
          <p><%= user.first_name %></p>
        </div>
        <h2 class="card-teacher-pricing">£ <%= (20..50).to_a.sample %>/hr</h2>
      </div>
    </div>
  <% end %>
  </div>

  <div
  id="map"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-markers="<%= @markers.to_json %>"
  ></div>


</div>

app/views/users/show.html.erb
<div class="container container-show">
  <div class="card-details">
    <div class="teacher-details">
      <div class="teacher-photo-name">
        <div class="profile-photo">
          <%= cl_image_tag(@user.photo, width: 220, height: 150) %>
        </div>
        <div class="name-users-show">
          <h1><%= @user.skill %></h1>
          <h3><%= @user.first_name %></h3>
        </div>
        <div class="price">
          <h3>£<%= (20..50).to_a.sample %></h3><h2>an hour</h2>
        </div>
      </div>
      <div class="price-story">
        <div class="story">
          <h3>About me</h3>
          <hr class="line-show">
          <p><%= @user.biography %></p>
        </div>
      </div>
    </div>
       <div class="map-user"
      id="map"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-markers="<%= @markers.to_json %>"
      ></div>
  </div>
  <div class="buttons-users-show">
    <%= link_to "Back to teacher search", users_path, class: "btn btn-all-teachers btn-user" %>
    <% if params[:id].to_i != current_user.id %>
      <%= link_to "Request this teacher", new_user_booking_path(@user), class: "btn btn-secondary btn-card btn-booking-teacher" %>
    <% end %>
  </div>

</div>